[programs.localnet]
hydra = "DtvtjfmqH3yrPbTyxCjzpPdZwkcAcUu1edwPThkmLxv9"

[programs.devnet]
hydra = "DtvtjfmqH3yrPbTyxCjzpPdZwkcAcUu1edwPThkmLxv9"

[programs.mainnet]
hydra = "DtvtjfmqH3yrPbTyxCjzpPdZwkcAcUu1edwPThkmLxv9"
[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"



